<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK58OC8P\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK58OC8P/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerK58OC8P.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerK58OC8P\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerK58OC8P\App_KernelProdContainer([
    'container.build_hash' => 'K58OC8P',
    'container.build_id' => 'acd0ce1b',
    'container.build_time' => 1719884448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK58OC8P');
