<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'app_booking' => [[], ['_controller' => 'App\\Controller\\BookingController::book'], [], [['text', '/booking']], [], [], []],
    'app_commentaire_modifier' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::update'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/modifier_commentaire']], [], [], []],
    'app_commentaire_supprimer' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::delete'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/supprimer_commentaire']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\HomeController::contact'], [], [['text', '/contact']], [], [], []],
    'app_cgu' => [[], ['_controller' => 'App\\Controller\\HomeController::mention'], [], [['text', '/cgu']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\SecurityController::profil'], [], [['text', '/profil']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_passer_en_admin' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::passerEnAdmin'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/passer_en_admin']], [], [], []],
    'app_taxis_add' => [[], ['_controller' => 'App\\Controller\\TaxisController::addTaxi'], [], [['text', '/add_taxi']], [], [], []],
    'app_taxis' => [[], ['_controller' => 'App\\Controller\\TaxisController::listetaxi'], [], [['text', '/taxis']], [], [], []],
    'app_taxi' => [['id'], ['_controller' => 'App\\Controller\\TaxisController::oneTaxi'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/taxi']], [], [], []],
    'app_taxis_gestion' => [[], ['_controller' => 'App\\Controller\\TaxisController::gestionTaxi'], [], [['text', '/gestionTaxis']], [], [], []],
    'app_taxi_update' => [['id'], ['_controller' => 'App\\Controller\\TaxisController::update'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/update_taxi']], [], [], []],
    'app_taxi_delete' => [['id'], ['_controller' => 'App\\Controller\\TaxisController::delete'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/delete_taxi']], [], [], []],
];
