<?php

namespace ContainerK58OC8P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DYJmacService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.d_yJmac' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_yJmac'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoCom' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'repoTax' => ['privates', 'App\\Repository\\TaxisRepository', 'getTaxisRepositoryService', true],
        ], [
            'repoCom' => 'App\\Repository\\CommentaireRepository',
            'repoTax' => 'App\\Repository\\TaxisRepository',
        ]);
    }
}
