<?php

namespace ContainerK58OC8P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingDetailRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BookingDetailRepository' shared autowired service.
     *
     * @return \App\Repository\BookingDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BookingDetailRepository'] = new \App\Repository\BookingDetailRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
