<?php

namespace ContainerK58OC8P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxisRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TaxisRepository' shared autowired service.
     *
     * @return \App\Repository\TaxisRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TaxisRepository'] = new \App\Repository\TaxisRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
