<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commentaire extends \App\Entity\Commentaire implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null],
        "\0".parent::class."\0".'dateDeCreation' => [parent::class, 'dateDeCreation', null],
        "\0".parent::class."\0".'dateDeModification' => [parent::class, 'dateDeModification', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'taxi' => [parent::class, 'taxi', null],
        'avis' => [parent::class, 'avis', null],
        'dateDeCreation' => [parent::class, 'dateDeCreation', null],
        'dateDeModification' => [parent::class, 'dateDeModification', null],
        'id' => [parent::class, 'id', null],
        'taxi' => [parent::class, 'taxi', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
