<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0ndjsv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0ndjsv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0ndjsv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0ndjsv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0ndjsv\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0ndjsv',
    'container.build_id' => 'd2dd19a9',
    'container.build_time' => 1719870609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0ndjsv');
