<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKNZYKt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKNZYKt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKNZYKt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKNZYKt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNKNZYKt\App_KernelDevDebugContainer([
    'container.build_hash' => 'NKNZYKt',
    'container.build_id' => 'e2b05740',
    'container.build_time' => 1719876682,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKNZYKt');
