<?php

namespace ContainerNKNZYKt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SRHoVhNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sRHoVhN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sRHoVhN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'repoDet' => ['privates', 'App\\Repository\\BookingDetailRepository', 'getBookingDetailRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\BookingRepository',
            'repoDet' => 'App\\Repository\\BookingDetailRepository',
        ]);
    }
}
